### DISCUSSION TITLE
Support initialization after creating a Helm deployment

### DISCUSSION THREAD

**Discussion by KodrAus** [datalust/seq-tickets#1089] [Ideas]
See: https://docs.datalust.co/discuss/5ef1f87fc1d6490230b10d96

Trying to script the post-deployment of Seq in Kubernetes can be a bit of a hassle. It might be possible to put something together using [init containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) that can either run a set of scripts from a directory, or just a shell script/binary that interacts with the Seq API.

**Comment by KodrAus** [comment]
We could lean on `seqcli` for this, and use a [config map](https://kubernetes.io/docs/concepts/configuration/configmap/) to store a set of scripts that call the CLI in a container that has a connection profile configured for the upcoming Seq instance:

```yaml
setup: 
  retention.ps1: |
    $signal = seqcli signal create --title 'Exceptions' --filter "@Exception is not null"
    seqcli retention create --signal-expression $signal
```
