### DISCUSSION TITLE
Convert CSS to us CSS Variables for Easy Customization

### DISCUSSION THREAD

**Discussion by rblackman** [datalust/seq-tickets#1329] [Ideas]
When customizing SEQ's CSS, it is very difficult to find all of the relevant rules if, for example, you want to change the monospace font. With CSS variables being well supported in [all modern browsers][1], it would be nice if the SEQ CSS could be refactored to use CSS variables for items that are commonly customized (e.g. fonts and colors). This would allow easy customization of SEQ just by setting a single CSS variable. For example, the CSS I had to use to change the monospace font was:

```css
code,
.source,
.labeled-term-input .labeled-term div.as,
.chart-query-editor .control-group .control-label,
input.source,
.chart-query-editor .control-group input.control-label,
input.source:active,
.chart-query-editor .control-group input.control-label:active,
input.source:focus,
.chart-query-editor .control-group input.control-label:focus,
.filter-editor > input,
.filter-editor > input:focus,
.cm-s-seq.CodeMirror,
.dashboard-list ul.list-items > li.list-item.group .group-header .item-title,
.ingestion-log-index pre.log-terminal,
table.inputs-table .custom-filter .custom-filter-prepend,
.instance-index .styles,
.license-index .license-text,
.alert-editor a.available-label,
.chart-table table .property-name,
.chart-table table .property-value,
.as-table table .property-name,
.event-columns .property-name,
.event-properties .property .property-name,
.filter-box .inset-controls .history .dropdown-menu ul li a,
.current-signal .items ul.filters > li .description.code,
.current-signal .items ul.filters > li .filter-editor input,
.current-signal .items .tags .tag .property-name,
.current-signal .items .grouping-editor .group-name,
.event-properties .property-value {
    font-family: 'Fira Code', Consolas, Monaco, monospace;
}
```

If the CSS was updated to use variables, the CSS could be as simple as:

```css
:root {
    --monospace-font: 'Fira Code', Consolas, Monaco, monospace;
}
```

It would also allow for customization to be much more easily documented, you would just need to provide a list of overwritable variables and what they do.

[1]: https://caniuse.com/css-variables
