### DISCUSSION TITLE
Config helm chart for using existing volume

### DISCUSSION THREAD

**Discussion by stonemonkey** [datalust/seq-tickets#1463] [Help] [answered]
Hi,
I have seq pod running in an AKS cluster. It was installed manually with a custom yaml looking like this:
```
apiVersion: v1
kind: Pod
metadata:
  name: seq
  labels:
    app: seq
spec:
  nodeSelector:
    "kubernetes.io/os": linux
  containers:
  - name: seq
    image: datalust/seq:2021.4
    resources:
      requests:
        memory: 3Gi
        cpu: 1000m
      limits:
        memory: 3Gi
        cpu: 1000m
    ports:
    - containerPort: 80
    - containerPort: 5341
    env:
    - name: ACCEPT_EULA
      value: "Y"   
    volumeMounts:
    - mountPath: "/data"
      name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: seq-managed-disk
```

I'd like to use the helm chart for installing seq. The existent installation has a persistent volume claim with a volume associated which I'd like to keep. 

How can I specify that in the helm `config.yaml`?

Regards,
/Costin
