### DISCUSSION TITLE
Fail to enable GELF logs for containers in docker-compose.yml

### DISCUSSION THREAD

**Discussion by yooakim** [datalust/seq-tickets#1597] [Help] [answered]
Hi friends,
I am trying to setup a docker-compose file to enable me to start Seq, Seq-GELF input and some services. I want to collect all the container logs as well as have the container apps to send logs to Seq (often using Serilog sink). 

The idea is to have a single `docker compose up` command that launches Seq, seq-input-gelf and services to send all logs to the Seq instance defined in the docker-compose file. 

I've tried this in a number of different ways but it fails during startup.

What I can't seem to get working is to ensure the Seq and seq-input-gelf is started before the other containers. So for some reason I get this error when I do `docker compose up` 

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/862546/176696400-679ac184-ea6a-4a92-b577-5d48ae1cec83.png">

I really appreciate help here, not sure why the order and `depends-on` aren't respected?

My `docker-compose.yml` is as follows:
```
version: '3.8'

# Use extension field to only specify this once
x-logging: 
      &seq-logging
      driver: "gelf"
      options:
        gelf-address: "udp://host.docker.internal:12201"

services:
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: 'Y'
      restart: unless-stopped
    volumes:
      - ./seq-data:/data

  seq-input-gelf:
    image: datalust/seq-input-gelf:latest
    depends_on:
      - seq
    ports:
      - "12201:12201/udp"
    environment:
      SEQ_ADDRESS: "http://seq:5341"
    restart: unless-stopped


  db:
    image: postgres
    depends_on:
    - seq-input-gelf

    restart: always
    environment:
      POSTGRES_USER: dbauser
      POSTGRES_PASSWORD: dbauserpassword
      POSTGRES_DB: devdb
    logging: *seq-logging

  adminer:
    image: adminer
    depends_on:
    - seq-input-gelf
    restart: always
    ports:
      - 8080:8080
    logging: *seq-logging

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    depends_on:
      - seq-input-gelf
    restart: unless-stopped
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    logging: *seq-logging

```
