### DISCUSSION TITLE
Advise to ingest syslogs from a Debian Box? I seem to miss the obvious ..

### DISCUSSION THREAD

**Discussion by wechsler42** [datalust/seq-tickets#1599] [Help]
Hi there
It must be something obvious but unfortunately, I am still missing it. So I dare to ask for something like a short step for step advise on how to get the syslogs of a Debian box  ingested in seq. 
The situation:

PC A: 
Seq and seq-input-syslog are up and running in a Docker installation. For example the Application Health Checks of some of my services work flawlessly in Seq.
For Syslog collection, I added this section for "seq-input-syslog" to my seq docker-compose file:

```
  seq-input-syslog:
    image: datalust/seq-input-syslog:latest
    depends_on:
      - seq
    ports:
      - "514:514/tcp"
    environment:
      SEQ_ADDRESS: http://seq:5341/
      SYSLOG_ADDRESS: tcp://192.168.Y.XX:514
    restart: unless-stopped
```

PC B:
(192.168.Y.XX), the Debian Box without Docker
Rsyslog is up and running according to “systemctl status rsyslog”
/var/log/ is filled with different logs

What do I have to install and/or configure that this Debian Box sends the syslog to Seq in PC A?
Thanks in advance for guidance.
