### DISCUSSION TITLE
Using Ingress paths to show UI in Kubernetes

### DISCUSSION THREAD

**Discussion by mkoziel2000** [datalust/seq-tickets#1691] [Help]
Instead of creating multiple external DNS addresses for each seq instance we deploy, we'd like to avoid getting IT involved every time we want to create a temp instance of seq by using ingress pathing to discern one temporary seq install from another (https://mydomain/joeprivate/seq vs https://mydomain/sueprivate/seq).  Using ingress paths is our general pattern for how we've done this with other services.  We leverage the nginx.ingress.kubernetes.io/x-forwarded-prefix annotation in ingress definition to allow our UI services to apply the appropriate base paths to URLs it constructs for the browser.  It seems the seq UI doesn't adhere to this.  Instead, we see it dropping the last part of the path when it constructs URL paths to be sent to the client browser.  

Is there anyway we can do with this pathing or do we need to expose every instance of seq as a DNS record?

**Comment by mkoziel2000** [comment]
After submitting this discussion, I found a SEQ_BASE_URI environment variable that gets me the path rewrite behavior I was looking for.  Looks like its also exposed in the helm chart values.yaml as "baseUri:"...I totally missed this when reviewing the chart.  It seems to allow the UI to render properly when ingress paths are used instead of specifying unique DNS host names.  I did have to add a configuration-snippet to the ingress to get everything to work if the url was missing a trailing slash in its path, but adding that in addition to the baseUrl environment variable seem to clear everything up:

ingress.yaml -

```
metadata:
  name: seq
  namespace: development-seq
  annotations:
    meta.helm.sh/release-name: seq
    meta.helm.sh/release-namespace: development-seq
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: rewrite ^(/dev/seq)$ $1/ redirect;
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mydomain.com
      secretName: letsencrypt-cert-seq
  rules:
    - host: mydomain.com
      http:
        paths:
          - path: /dev/seq(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: seq
                port:
                  number: 80
```
