### DISCUSSION TITLE
Is SEQ_CACHE_SYSTEMRAMTARGET aware of pod limits?

### DISCUSSION THREAD

**Discussion by taspeotis** [datalust/seq-tickets#1756] [Help]
We use Seq via Helm. Recently we have noticed the pod restarting due to the OOM killer:

```
terminated
Reason:Reason: OOMKilled - exit code: 137
```

Seq is indeed using a lot of memory:

![image](https://user-images.githubusercontent.com/1189399/216857464-f4f10560-06fb-46e2-b266-31b88c15a280.png)

The pod spec is as follows:

```yaml
  containers:
    - name: seq
      image: datalust/seq:2023.1.8829
      ports: [ ... ]
      env:
        [ ... ]
        - name: SEQ_CACHE_SYSTEMRAMTARGET
          value: '0.9'
      resources:
        limits:
          memory: 8Gi
        requests:
          memory: 8Gi
```

There's documentation [here](https://docs.datalust.co/docs/docker-memory) and a discussion [here](https://github.com/datalust/seq-tickets/issues/1020) about setting `--memory(-swap)` for Docker but Kubernetes doesn't use Docker anymore.

I thought it was 2023.1 but I downgraded to 2022.1 and see the same symptoms: memory usage greatly exceeds the limit.

My expectation is `SEQ_CACHE_SYSTEMRAMTARGET` is relative to the pod limits, also I understand if Seq can't learn what its pod limit is it's not going to do what I want.

1. Is there something I have to configure other than pod limits?
2. Alternatively is SEQ_CACHE_SYSTEMRAMTARGET always relative to the node memory, rather than the pod?

Thanks in advance!
