### DISCUSSION TITLE
CLI usage for Seq in Kubernetes

### DISCUSSION THREAD

**Discussion by kellybirr** [datalust/seq-tickets#1827] [Show and tell]
Earlier today I had to reset auth on a Seq install in AKS where my Azure AD secret for authentication had expired.  While I was in there, I also wanted to migrate my metadata to MS-SQL.

If you have Seq deployed via a Kubernetes deployment, you can't use the CLI easily.  If use `kubectl exec ...` to get a shell on the container, you can run the CLI but it won't work, because the service is running, and the files are locked.  If you kill the service, the container restarts, kicking you out and starting the service back up.

The solution is to scale your Seq deployment down to 0 instances, then deploy a Kubernetes Job, using the Seq container, mounting the same persistent volume claim and running the CLI command instead of the container default (the service).

Here are the two YAMLs I used to do this.  You may want to incorporate this into your documentation for Kubernetes users.

**Migrate to SQL**
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: seq-sql-migrate
spec:
  template:
    spec:
      containers:
      - name: seq
        image: datalust/seq
        command: ["seqsvr",  "metastore", "to-mssql", "--connection-string", "<connection-string>", "--skip-config"]
        env:
        - name: ACCEPT_EULA
          value: "Y"
        volumeMounts:
        - name: seq-data
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: seq-data
        persistentVolumeClaim:
          claimName: seq-volume-claim
```
In the manifest above you will put your actual connection string instead of "\<connection-string\>".  Also you need to use the proper persistent volume claim, mine is "seq-volume-claim".

**Reset Auth (metadata in SQL)**
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: seq-reset-auth
spec:
  template:
    spec:
      containers:
      - name: seq
        image: datalust/seq
        command: ["seqsvr",  "auth", "reset", "-u", "admin@mycompany.com", "-p", "<password>"]
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SEQ_METASTORE_MSSQL_CONNECTIONSTRING
          value: "<connection-string>"
        volumeMounts:
        - name: seq-data
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: seq-data
        persistentVolumeClaim:
          claimName: seq-volume-claim
```

Similar to before put in an actual password instead of "\<password\>" and use the right volume claim name.  
Also, this YAML works for non-SQL by removing the SEQ_METASTORE_MSSQL_CONNECTIONSTRING environment variable.  To use sql, replace the "\<connection-string\>" value.
