### DISCUSSION TITLE
Docker - Unable to get https working

### DISCUSSION THREAD

**Discussion by claytonjs** [datalust/seq-tickets#1882] [Help] [answered]
Hi, I'm unable to get https working for Seq on Docker and so far am stumped as what I'm missing or doing wrong.

My Docker yml file is as follows:

```
version: '3'
name: seq
services:
  seq-input-syslog:
    container_name: syslog
    image: datalust/seq-input-syslog:latest
    depends_on:
      - seq
    ports:
      - "514:514/udp"
    environment:
      SEQ_ADDRESS: "http://seq.xxxx.ca:5080"
    restart: unless-stopped
  seq:
    container_name: seq
    image: datalust/seq:latest
    ports:
      - "5080:80"
      - "5443:443"
      - "5341:5341"
    environment:
      ACCEPT_EULA: Y
      TZ: America/Edmonton
    restart: unless-stopped
    volumes:
      - /docker/seq:/data

```
And in my Seq.json has the following set:
`"redirectHttpToHttps": true,`

and

```
  "certificates": {
    "certificatesPath": /Certificates,
    "defaultPassword": null
  },
```

And under my cert path I have my .pem files. (I wasn't sure if the naming of the port mattered, so I've done both).

```
:/docker/seq/data/Certificates$ pwd
/docker/seq/data/Certificates
:/docker/seq/data/Certificates$ ls -ltrh
total 16K
-rw-r--r-- 1 root root 2.3K Jun 29 09:57 443.pem
-rw------- 1 root root 1.7K Jun 29 09:57 443-key.pem
-rw-r--r-- 1 root root 2.3K Jun 29 10:26 5341.pem
-rw------- 1 root root 1.7K Jun 29 10:26 5341-key.pem
:/docker/seq/data/Certificates$
```

Any help would be greatly appreciated.

Cheers.
Clayton
