### DISCUSSION TITLE
Configure Seq backup directory

### DISCUSSION THREAD

**Discussion by dazinator** [datalust/seq-tickets#1888] [Help]
I'm migrating to docker.
I'd very much like to be able to configure a different `Backups` directory location. I can't see a way to do this from the docs: https://docs.datalust.co/v2021.1/docs/json-config It looks like seq will always use `{StorageRoot}/Backups`

I will try to explain my reasons..
I'd like for the backups to actually be persisted to a file share. This makes recovery on another node easier. With docker I can already achieve this like so:

```
volumes:
  data:
    driver: local
  share:
    external: true
    name: share-we

services:
  seq:
    image: datalust/seq:2021.1.5282    
    environment:
      - ACCEPT_EULA=Y     
      - SEQ_STORAGE_SECRETKEY=${SEQ_STORAGE_SECRETKEY}
    volumes:
      - data:/data
      - share-we:/data/Backups

```

Here the volume `share-we` is a docker volume created as an external volume and backed by a CIFS volume driver.

So what is my problem? Well the issue is that `docker` won't let you [mount a sub directory of a named volume](https://github.com/moby/moby/issues/32582). So for example, where I have several containers running on the same node, all mounting the same file share volume, by default I can only mount the root of the file share into a mount point of the container. In this case I can only map the root of the file share into /data/Backups mount point in seq container. But this means that seq will be outputting it's backups to the root of the file share - and I would prefer to keep things organised, and instead have a subfolder for seq. In other words I would like to configure the seq backups directory to be `/data/Backups/seq` and that way I can mount my file share to `/data/Backups` and seq backups will be output to a seq subfolder rather that on the root.

Is this possible today? (and specifically in v2021.1)
