### DISCUSSION TITLE
Setting dot colors

### DISCUSSION THREAD

**Discussion by MelGrubb** [datalust/seq-tickets#1996] [Help]
Normally my search skills are pretty good, but I've combed through the docs looking for this and somehow I'm not seeing it. Is there any way to set the dot color for a signal? I have added a few custom signals, and it would be very helpful if the dots next to the messages could be set somehow. Short of hacking around with the style sheets, is there any way to say that, for example, my "Debug" signal should have a green dot?

**Comment by nblumhardt** [comment]
Hi! Yes, this is possible. Assuming that your "Debug" signal is in the "Level" group, the rule will be:

```
body.dark-theme .signal-list ul.signals li.group > ul.signals > li.signal.level-debug .icon-signal .center {
    fill: green;
}

body.light-theme .signal-list ul.signals li.group > ul.signals > li.signal.level-debug .icon-signal .center {
    fill: green;
}
```

You can put this in Settings > Instance.

Each signal's `li.signal` element gets a generated class added to it of the form `{group-}name` in lower case.

Hope this helps!

**Reply by NameOfTheDragon** [reply]
Is this still valid as of 2024.2 release? I have a level called "Note" and I can't seem to give it a coloured dot.....?
![image](https://github.com/datalust/seq-tickets/assets/1268490/e95e38f9-3bbc-42a0-afec-b405936c6869)

using this CSS:
```css
body.dark-theme .signal-list ul.signals li.group > ul.signals > li.signal.level-note .icon-signal .center {
    fill: green;
}

body.light-theme .signal-list ul.signals li.group > ul.signals > li.signal.level-note .icon-signal .center {
    fill: green;
}
```

**Reply by liammclennan** [reply]
Hi @NameOfTheDragon 

This thread seems to be about setting the color of signals. 

To set the style of a log level indicator try something like:

```css
div.message .level-indicator.seq-level-note {
  background-color: green;
}
```
