### DISCUSSION TITLE
How to logging output to json format?

### DISCUSSION THREAD

**Discussion by fuine6** [datalust/seq-tickets#1997] [Help] [answered]
Charts like prometheus allow me to set the json format, which helps filter logs.
```
prometheus:
  server:
    extraArgs:
      log.level: "warn"
      log.format: "json"
```

Is there currently a way to do this with seq?
