### DISCUSSION TITLE
Seq in docker swarm failing to start after redeployment: "invalid frame identifier"

### DISCUSSION THREAD

**Discussion by Toudahl** [datalust/seq-tickets#2069] [Help] [answered]
Hello,

I have just made a change in my infrastructure.yml to specify networks on various part of my, well, infrastructure.
After doing this, seq is unable to start - and i am getting an error that i do not think is caused by the network change.

Perhaps it is related to me using nfs for my data volume? I understand it is not the recommended approach, but i thought i would try anyway, since this is just a hobby project

Here is infrastructure.yml, with anything but seq removed.

```
version: '3.9'
services:
  seq:
    image: datalust/seq:2023.4.10949
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - ACCEPT_EULA=Y
      - SEQ_API_CANONICALURI=https://logs.mydomain.eu
    volumes:
      - seq-data:/data
    networks:
      - infrastructure-net

volumes:
  seq-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nfs.mydomain.eu,rw,nfsvers=4,async
      device: :/volume3/docker/datalust-seq-data

networks:
  infrastructure-net:
    driver: overlay
```

This is the error message i am seeing in the container logs:
```
Flare native storage failed (InternalError), failed to read a document collection.
infrastructure_seq.1.yk5xvm5lqk5k@rpi4-02    |    caused by: error attempting to open a document collection
infrastructure_seq.1.yk5xvm5lqk5k@rpi4-02    |    caused by: could not open document collection
infrastructure_seq.1.yk5xvm5lqk5k@rpi4-02    |    caused by: failed to open a document collection
infrastructure_seq.1.yk5xvm5lqk5k@rpi4-02    |    caused by: a frame in the key-value store could not be read
infrastructure_seq.1.yk5xvm5lqk5k@rpi4-02    |    caused by: invalid frame identifier: `0`
```
