### DISCUSSION TITLE
Is there an env variable to set a custom HTTP port

### DISCUSSION THREAD

**Discussion by rodneytamblyn** [datalust/seq-tickets#2164] [Help] [answered]
I am attempting to setup a container group so I can use Caddy as a sidecar container for HTTPS.

This requires that SEQ http not be on port 80 - as the sidecar will map ports 80 and 443 and forward traffic on localhost to the seq container.

Is there an env variable I can use in the container create step to define the http port for seq to something non-default - e.g. port 5000

Example YAML (partial)
```
    - name: my-container-group-name
      properties:
        image: 'datalust/seq:latest'
        ports:
          - port: 5000 # the port I want to serve SEQ http on
            protocol: TCP
        environmentVariables:
          - name: HOST_HTTP_PORT # ? 
            value: 5000
          - name: ACCEPT_EULA
            value: 'Y'
          - name: SEQ_API_CANONICALURI
            value: 'http://xxxxx.australiaeast.azurecontainer.io/'
```
