### DISCUSSION TITLE
Does seq syslog require me to add a syslog container when seq is deployed in container instance

### DISCUSSION THREAD

**Discussion by rodneytamblyn** [datalust/seq-tickets#2197] [General]
I am attempting to enable Seq Syslog logging following https://docs.datalust.co/docs/syslog
My instance of Seq is deployed in docker as a multi-container instance: https://github.com/datalust/seq-tickets/discussions/2148#discussioncomment-9128710

Will I need to redeploy my Seq instance adding a seq-input-syslog container, or is it sufficient just to install the Seq syslog app in the Seq instance?

```
services:
  seq-input-syslog:
    image: datalust/seq-input-syslog:latest
    depends_on:
      - seq
    ports:
      - "514:514/udp"
    environment:
      SEQ_ADDRESS: "http://seq:5341"
    restart: unless-stopped
```
