### DISCUSSION TITLE
How to set up healthcecks for the datalust/seq docker container in docker-compose?

### DISCUSSION THREAD

**Discussion by ddjerqq** [datalust/seq-tickets#2402] [Help]
I have been searching through the web and I can't find a satisfying answer about how to set up health checks for seq.

I tried using:
```yaml
healthcheck:
  // both
  test: ['CMD-SHELL', 'curl --insecure --silent --fail http://127.0.0.1:80/health || exit 1']
  // of these
  test: ['CMD-SHELL', 'wget --no-check-certificate --spider -q https://127.0.0.1:443/health || exit 1']
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 30s
```

but neither curl nor wget is installed in the seq container, so how do i enable healthchecks for seq?

how do i healthcheck the seq container itself? this is for a home lab, just for hobby projects. thanks in advance!

**Comment by ddjerqq** [comment]
right now i am using a rather smelly approach of:
```yaml
test: ["CMD-SHELL", "ps aux | grep 'seqsvr' | grep -v grep || exit 1"]
```

**Comment by nblumhardt** [comment]
Hi! The proper way to do this is something like:

```yaml
    healthcheck:
      test: "/seqsvr/Client/seqcli node health -s http://localhost"
      interval: 15s
      timeout: 10s
      retries: 2
      start_period: 5s
```

If this doesn't work, pull the `datalust/seq:preview` tag - it has the most up-to-date `seqcli` build in there, and will work with the command line above.

HTH!
