### DISCUSSION TITLE
Add back old light theme as an option

### DISCUSSION THREAD

**Discussion by c0shea** [datalust/seq-tickets#2424] [Ideas]
I understand the need for providing a new light theme that is more accessible for folks that need it, however it's not nearly as pretty of a UI anymore. Everything feels so much more boxy and rigid in the new theme. Could the old light theme be added back as an option to select in the user theme preference?

Some of the things we've trained users to look for are no longer valid in this new theme. For example, looking for yellow highlighting over properties on messages to know it's a placeholder. Now, it's purple text that is indistinguishable from the black text for the rest of the message.

**Comment by nblumhardt** [comment]
Hi @c0shea, thanks for the feedback. Good to know about the placeholder coloring issue, we'll take a look at that 👍 

Here's my version of the "Classic" theme, on 2025.1:

![image](https://github.com/user-attachments/assets/44f64ca8-6867-404e-8360-9a88fd61e744)

How does this look for you? Here's the CSS, which you can paste into Settings > General > Style overrides:

```css
body.light-theme.light-theme.light-theme {
  --active-theme-top-bar-canvas: #3c353c;
  --active-theme-side-bar-canvas: #242430;
  --active-theme-canvas: #fff;
  --active-theme-top-bar-input-canvas: #463f46;
  --active-theme-canvas-low: #f0f0f0;
  --active-theme-link-focus: #0ac6a4;
  --active-theme-link-item-canvas: #32796f;
  --active-theme-link-focus-intersect: #00eddb;
  --active-theme-link: #265559;
  --active-theme-link-active: #265559;
  --active-theme-link-item-canvas-focus: #0ac6a4;
  --active-theme-play: #0ac665;
  --active-theme-input-border: #ccc;
  --active-theme-btn-label: #676767;
  --active-theme-btn-border: #ccc;
  --active-theme-canvas-high: #fff;
}
 
body.light-theme .event.expanded {
  background-color: #e8fffb;
  border-left-color: #5ffaee;
}

body.light-theme .event.expanded.seq-level-error, body.light-theme .event.expanded.seq-level-fatal {
  background-color: #fff1f0;
  border-left-color: #ff5081;
}
 
body.light-theme .rendered-message .token {
  color: #444;
  background-color: #fffff1;
}

body.light-theme .event polygon.tick {
  fill: green;
}

body.light-theme .event polygon.cross {
  fill: red;
}
```

As you can see, there are a few things without variables covering them, but it's pretty close. Would you be so kind as to take a look, and if there are any tweaks you feel should be made, let me know? We've had a couple more similar requests, so I think we're on board with shipping a Classic variant in the box.
