### ISSUE TITLE
Base theme appears to override custom CSS

### ISSUE THREAD

**Issue by NameOfTheDragon** [datalust/seq-tickets#1002]
I was trying to cusomize the event colours shown by Seq. I found a discussion that explained how to do this with css. So I have created entries similar to this:

```lang=css
.level-indicator.seq-level-information {
    background-color: darkseagreen;
}
```

However, this does not work. Looking in the browser DevTools window, you can see that the correct CSS is there, but it has been overridden by the base theme (Dark):
![image](https://user-images.githubusercontent.com/1268490/88352649-74465480-cd52-11ea-82f8-bfdd31c56b2b.png)

If I add the `!important` keyword to my custom CSS then this situation reverses and the colours show up as expected. So this is a workaround: add `!important` to custom CSS.

However, it is mentioned in several places in the UI and documentation that custom CSS overrides the base style, so this is clearly not the intent. There seems to be a CSS ordering issue.

**Comment by larenelg** [comment]
Thanks @NameOfTheDragon for pointing this out! `!important` is never a nice work-around. We'll take a closer look 🙏

**Comment by nblumhardt** [comment]
Hi @NameOfTheDragon - I think the snippet for setting level colors is for a slightly earlier Seq version; to set level colors in all themes in 5.x and later, you'll need something along the lines of:

```css
body.dark-theme .level-indicator.seq-level-information, body.light-theme .level-indicator.seq-level-information {
    background-color: darkseagreen;
}
```

Let us know how you go! :-)
