### ISSUE TITLE
"Prefer AM/PM formatting" causes timestamps to wrap for some dates/times

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#1558]
![image](https://user-images.githubusercontent.com/342712/165182293-33f0f259-6c64-4ab0-815b-1c8bc2eff484.png)

To work around this temporarily, you can apply the following styles in _Settings > Instance_:

```css
.event .timestamp {
  width: 170px;
}

.event .description {
  padding-left: 175px;
}
```
