### ISSUE TITLE
Limit ingestion to the specific port doesn't work

### ISSUE THREAD

**Issue by alishchytovych** [datalust/seq-tickets#1567]
Using SEQ (seq:latest) in Kubernetes, with the container settings:
```
env:
            - name: "ACCEPT_EULA"
              value: "Y"
            - name: "SEQ_CACHE_SYSTEMRAMTARGET"
              value: "0.6"
            - name: "SEQ_API_INGESTIONPORTS"
              value: "5341"
            - name: "SEQ_API_LISTENURIS"
              value: "http://0.0.0.0:5000, http://0.0.0.0:5341"
```
allows events ingestion on 5000 port.

In the diagnostic report I see the following:
```
====================
10. Server Configuration
--------------------
Instance Name                 : <null>
Base URI                      : http://0.0.0.0:5000
Canonical URI                 : <null>
Listen URIs                   : http://0.0.0.0:5000, http://0.0.0.0:5341
Ingestion Ports               : 5341
Using SQL Metastore           : No
Using PostgreSQL Metastore    : No
Indexer Priority              : 0.0
Query Parallelism             : 4
Disk Reader Limit             : 5
Enabled Features              :
```

Expected result: port 5000 should not accept any ingestions (provide UI only).
Actual result: serilog successfully posts events to SEQ via 5000 port.
