### ISSUE TITLE
Logs removing intended spaces

### ISSUE THREAD

**Issue by RodrigoFerretti** [datalust/seq-tickets#1595]
# Bug Description
When sending logs to seq using nodejs with winston, i noticed that the data displayed at localhost:5341 doesnt have the intended space in log message

# Reproducing it

Create `docker-compose.yml` file:

```yaml
version: '3'
services:
  seq-input-gelf:
    image: datalust/seq-input-gelf:latest
    depends_on:
      - seq
    ports:
      - "12201:12201/udp"
    environment:
      SEQ_ADDRESS: "http://seq:5341"
    restart: unless-stopped
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: Y
    restart: unless-stopped
    volumes:
      - ./seq-data:/data`
  ```
Run in terminal:

```bash
docker-compose up -d
```
Create `tests.ts` typescript file:

```typescript 
import winston from 'winston';
import { SeqTransport } from '@datalust/winston-seq';

const logger = winston.createLogger({
    level: 'info',
    transports: [
        new winston.transports.Console({
            format: winston.format.simple()
        }),
        new SeqTransport({
            serverUrl: 'http://localhost:5341',
            onError: (e) => {
                console.error(e);
            },
            handleExceptions: true,
            handleRejections: true
        })
    ]
});

const message: object = {
    message:
        '[15:47:12] INFO:     test 1                                                                            --:--:--.---   '
};

logger.info(message);
```

Run in terminal 

```bash
yarn nodemon --watch server --exec ts-node test.ts
```

# Expected behavior
Log message string be exactly as sent from nodejs or at least a way of turning this condition on and off

# Screenshots
Terminal output: 
![image](https://user-images.githubusercontent.com/74201114/175648124-42027e0c-edbe-46cb-ab8e-dc68f40eaab7.png)

Seq output:
![image](https://user-images.githubusercontent.com/74201114/175648153-26340014-01d5-4a31-af3a-5a2943c1f700.png)

# Environment
 - OS - Ubuntu 20.04.3 LTS
 - Browser - Chrome
 - Seq Version - Seq 2022.1.7647
 - Using Docker? Yes

**Comment by liammclennan** [comment]
Hi Rodrigo,

If you expand the event in Seq and choose 'Export' -> 'Copy Raw JSON' you should get a `@mt` property with all of your spaces preserved.

The spaces are there, but Seq is a web app and HTML collapses adjacent spaces. If you replace the spaces in your message with `&nbsp;` then you will see the spaces. 

```javascript
'[15:47:12] INFO:&nbsp;&nbsp;&nbsp;&nbsp; test 1' 
```

Hope that helps.

**Comment by nblumhardt** [comment]
Hi @RodrigoFerretti ;

Just reviewing this again with Liam, the above suggestion won't work because Seq will escape any `&` characters that appear in the message.

Under _Settings > Instance_, in the Seq UI, you can paste the following CSS into the "Style overrides" text box, to achieve what you're after:

```css
.rendered-message {
  white-space: pre-wrap !important;
}
```

Seq doesn't do this by default, because embedded whitespace in messages can make a bit of a mess of the layout.

Another option, if you'd like to keep the "clean" default events view, but show spaces/newlines when an event is expanded, is to use:

```css
.expanded .rendered-message {
  white-space: pre-wrap !important;
}
```

instead.

Let us know if this helps! :-)
