### ISSUE TITLE
ExceptionDetails destructured from 2024.1 resulting in a very big log message

### ISSUE THREAD

**Issue by Staijn1** [datalust/seq-tickets#2085]
**Describe the bug**
I use the Serilog.Exceptions nuget package to add ExceptionDetails to Serilog messages.
I've noticed that from Seq version 2024.1 the ExceptionDetail is no longer shown as an object, which makes an exception message huge. I'm wondering if what I found is a setting in seq, or if this is a bug.

**To Reproduce**
1. Setup docker seq instances with different versions (2023.4 and 2024.1) (docker-compose):
```yaml
version: "3.8"

services:
  seq2023:
    image: datalust/seq:2023.4
    container_name: seq2023
    environment:
      ACCEPT_EULA: 'Y'
      SEQ_FIRSTRUN_ADMINPASSWORD_HASH: "admin"
    ports:
      - 5342:80
      - 5343:5341
    volumes:
      - ./SEQVolume2023:/data
  seq2024:
    image: datalust/seq:2024.1
    container_name: seq2024
    environment:
      ACCEPT_EULA: 'Y'
      SEQ_FIRSTRUN_ADMINPASSWORD_HASH: "admin"
    ports:
      - 5344:80
      - 5345:5341
    volumes:
      - ./SEQVolume2024:/data
```

3. Setup SerilogSerilog.Exceptions in a C# project to log to two seq instances with different versions
```C#
using Serilog;
using Serilog.Exceptions;

Console.WriteLine("Hello, World!");

var logger = new LoggerConfiguration()
    .Enrich.FromLogContext()
    .Enrich.WithExceptionDetails()
    // Seq version 2024.1 (Docker)
    .WriteTo.Seq("http://localhost:5341")
    // Seq version 2023.4 (Docker)
    .WriteTo.Seq("http://localhost:5342")
    .CreateLogger();


try
{
    // Throw an exception with ExceptionDetails
    throw new Exception("This is an exception");
} catch (Exception exception)
{
    logger.Error(exception, "Stopped program because of exception");
    throw;
}
finally
{
    Log.CloseAndFlush();
}
``` 

**Expected behavior**
A message with an expandable ExceptionDetails object, just like in 2023.5

**Screenshots**
Version 2023.4 (expected)
![image](https://github.com/datalust/seq-tickets/assets/20322714/0402ef79-82c1-4155-8759-d77068893563)

Version 2024.1
![image](https://github.com/datalust/seq-tickets/assets/20322714/78caeda7-e605-4abd-aede-2eb1b20a586d)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Seq Version 2024.1.11001 & 2023.4.10949
 - Using Docker? Yes
 

**Additional context**
For the simple exception thrown in this simple C# application, the message is not that big. But for exceptions that have large InnerExceptions, the message will become huge, like what is happening in my real application. The exception thrown here is a Foreign Key constraint thrown by Entity Framework. The Serilog.Exceptions.EnityFramework is also set up for this project.
![image](https://github.com/datalust/seq-tickets/assets/20322714/536a2a34-51be-4d46-809e-276788280eae)
