### ISSUE TITLE
BASE_URI does not set relative path in index.html

### ISSUE THREAD

**Issue by cristiz1992** [datalust/seq-tickets#2448]
**Describe the bug**
In kubernetes, setting the BASE_URI or SEQ_API_CANONICALURI to https://example.com/seq does not generate in the index.html the correct relative path prefix /seq for the other resources like css or javascript files.

**To Reproduce**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
  namespace: seq-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seq
      release: seq
  template:
    metadata:
      labels:
        app: seq
        release: seq
    spec:
      containers:
        - name: seq
          image: datalust/seq:2024.3
          ports:
            - name: ingestion
              containerPort: 5341
              protocol: TCP
            - name: ui
              containerPort: 80
              protocol: TCP
          env:
            - name: ACCEPT_EULA
              value: 'Y'
            - name: SEQ_FIRSTRUN_REQUIREAUTHENTICATIONFORHTTPINGESTION
              value: 'true'
            - name: BASE_URI
              value: https://example.com/seq/
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
            runAsUser: 0
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
```

**Expected behavior**
Files like theme/styles.css should resolve to https://example.com/seq/theme/styles.css

**Comment by KodrAus** [comment]
Hi @cristiz1992 👋 

The URIs for resources in Seq’s `index.html` are relative, so the browser should request them under the same subpath you’re accessing Seq on.

Do you have an ingress acting as a reverse proxy or are you exposing it directly?

**Comment by cristiz1992** [comment]
I'm using traefik as ingress controller. This is the ingress used:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seq
  namespace: seq-system
  labels:
    app: seq
    release: seq
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: seq-system-stripseqprefix@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: example.com
      http:
        paths:
          - path: /seq
            pathType: Prefix
            backend:
              service:
                name: seq
                port:
                  number: 80
```

With middleware stripseqprefix the index.html returns fine. Without it I get 404.
```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripseqprefix
  namespace: seq-system
spec:
  stripPrefix:
    prefixes:
      - /seq
```

I've tried in firefox, chrome and edge and in all of them the javascript and css files are returning 404.

**Comment by cristiz1992** [comment]
If I set in browser the url to end with '/' then it works https://example.com/seq/
If I omit the last '/' then for each js or css resource it returns 404.

**Comment by cristiz1992** [comment]
Managed to make it work with these middlewares:
```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: appendtrailingslash
  namespace: seq-system
spec:
  redirectRegex:
    regex: ^(https?://[^/]+/seq)$
    replacement: ${1}/
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripseqprefix
  namespace: seq-system
spec:
  stripPrefix:
    prefixes:
      - /seq
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: seqprefixchain
  namespace: seq-system
spec:
  chain:
    middlewares:
      - name: appendtrailingslash
      - name: stripseqprefix
```
The magic is done by appendtrailingslash which matches the url without the trailing slash and appends it.
In the ingress I needed to update the middleware to use the chain one: seqprefixchain
`traefik.ingress.kubernetes.io/router.middlewares: seq-system-seqprefixchain@kubernetescrd`

Thanks [KodrAus](https://github.com/KodrAus) for your help.
