### ISSUE TITLE
Distinguish Verbose vs Debug and Error vs Fatal events

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-tickets#638]
In the event list, the difference between Debug / Information / Warning / Error is pretty obvious ... but Debug events look the same as Verbose events, and Error events look the same as Fatal events.

It would be nice to have a visible distinction because ... 
- some time we enable Debug logging-level in production to investigate, and that's fine and bearable ... but if we have Verbose events reaching prod, we really want to be aware of it so that we do not forget to move the log level limit back up after investigation
- Errors happen regularly ... but Fatal should be really special and need special attention 

Maybe a lighter gray would be nice for Verbose ... or a more subtle icon like a gray circle with an white fill.
For Fatal, maybe a different shape would help ? (like a little triangle to indicate danger)

Another option would be to make 
- Verbose messages a bit less opaque altogether
- Fatal messages written in bold or red or something

I guess there's also the option of hacking it via the CSS theming feature :) ... but I don't think there would be a CSS selector that would allow to target message contents based on the event's level ...

**Comment by nblumhardt** [comment]
Thanks for the suggestion; we're planning to do another "styling" pass before 4.2 is finished, which should be a good time to take a look at this.

**Comment by nblumhardt** [comment]
We've taken a look at this and, while we'd like to take a shot at it, it doesn't make the cut when stacked against the other backlog items we have open. (There's some effort involved in reviewing the variations across logging libraries for these levels, as well as design work for the colors.)

For the two scenarios you mention, `Verbose` events left on in prod, and rare-but-important `Fatal` errors, the apps, dashboarding and alerting features are a good option for detecting these problems.

To improve the display anyway, the theming feature works well:

```css
.level-indicator.seq-level-fatal {
    background-color: #000;
}
```

Closing for now, but thanks again for the suggestion, and let us know if you think we're missing anything in reaching this conclusion.

**Comment by tsimbalar** [comment]
I've been playing around a bit, so I thought I might as well share what I tried ... 

Here is what I ended up with :

- for **FATAL** events, a square indicator with capital letter `F` 

![image](https://user-images.githubusercontent.com/160544/34931345-9c954d24-f9ce-11e7-83bf-92227544d703.png)

with the following CSS : 

```css
/*Customize FATAL indicators (square + F) */
.level-indicator.seq-level-fatal{
	border-radius : 0;
}


.level-indicator.seq-level-fatal::after {
	content: "F";
	display: inline-block;
	width: 9px;
	height: 9px;
	float: left;
	vertical-align: middle;
	text-align: center;
	line-height: 8px;
	font-size: 7px;
	font-weight: bold;
	color: #fff;
}
```


- For **Verbose** events : 

Gray circle filled in white
![image](https://user-images.githubusercontent.com/160544/34932599-c1911310-f9d3-11e7-8296-0c9f8d9a3915.png)

with the following CSS : 
```css
/*Verbose indicator : gray circled filled with white */
.level-indicator.seq-level-verbose::after {
	content: "";
	display: inline-block;
	width: 7px;
	height: 7px;
	border-radius: 3.5px;
	background-color: white;
	float: left;
	margin: 1px;
}
```

or a gray circle with letter `V` in it 
![image](https://user-images.githubusercontent.com/160544/34932729-640cb6d0-f9d4-11e7-8b91-4556267fa583.png)

thanks to the following CSS : 

````css
/* Show verbose events as a gray circle with letter V */
.level-indicator.seq-level-verbose::after {
	content: "V";
	display: inline-block;
	width: 9px;
	height: 9px;
	float: left;
	vertical-align: middle;
	text-align: center;
	line-height: 8px;
	font-size: 7px;
	font-weight: bold;
	color: #fff;
}
```

or gray square with letter `V`in it
![image](https://user-images.githubusercontent.com/160544/34933007-8736200a-f9d5-11e7-9d73-c751de02e6f9.png)


with this CSS : 
```css
/* Show verbose events as a gray square with letter V */
.level-indicator.seq-level-verbose {
	border-radius: 0;
}
.level-indicator.seq-level-verbose::after {
	content: "V";
	display: inline-block;
	width: 9px;
	height: 9px;
	float: left;
	vertical-align: middle;
	text-align: center;
	line-height: 8px;
	font-size: 7px;
	font-weight: bold;
	color: #fff;
}
```
