### ISSUE TITLE
Checkbox state hard to discern for some users

### ISSUE THREAD

**Issue by nblumhardt** [datalust/seq-tickets#789]
The colored/transparent checkbox states are hard to differentiate, especially for users needing high-contrast or colorblind-friendly presentation, and especially when displayed over a colored background such as the checkbox at the top of _Settings > API keys_.

A traditional inset square/tick/cross would help with this.

**Comment by nblumhardt** [comment]
A temporary workaround is to include the following overrides in _Settings > Instance_:

```css
input[type="checkbox"] {
    -webkit-appearance: checkbox !important;
    -moz-appearance: checkbox !important;
    appearance: checkbox !important;
}
```
