### ISSUE TITLE
Liveness probe failure - Fix

### ISSUE THREAD

**Issue by tanwarsatya** [datalust/seq-tickets#912]
The default setting for the liveness probe is failing in the AKS cluster, as the container takes time to start even after the container started status. I had to increase the initial delay and timeout values for the liveness and readiness probe to get it worked without any issue.

```
livenessProbe:
  enabled: false
  failureThreshold: 3
  initialDelaySeconds: 120
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 60
readinessProbe:
  enabled: true
  failureThreshold: 3
  initialDelaySeconds: 120
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 60
```
