### ISSUE TITLE
helm chart: optionally expose ingestion port as service and on ingress

### ISSUE THREAD

**Issue by softlion** [datalust/seq-tickets#945]
This is an improvement request.
I host a seq server on my kubernetes cluster, installed using the seq helm chart.

The chart does not expose the ingestion port as a ClusterIP service not on the ingress, so seq ingestion is not available from outside the cluster.

It would be nice if this feature was built in.

```
 name: ingestion
 containerPort: 5341
```

**Comment by nblumhardt** [comment]
Thanks!

**Comment by KodrAus** [comment]
Hi @softlion :wave:

We've just updated the chart with a `2.0` release that supports ingress for the ingestion-only port. The shape of the `values.yaml` has changed slightly, but now you can do something like:

```yaml

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx

ui:
  ingress:
    enabled: true
    path: /
    hosts:
      - seq-dev.local
ingestion:
  ingress:
    enabled: true
    path: /
    hosts:
      - seq-dev-ingest.local
```

to expose the full API on `seq-dev.local` and the ingestion-only API on `seq-dev-ingest.local`.

**Comment by softlion** [comment]
Hi @KodrAus,
i just tried your chart.

Unfortunately it has issues with my current setup, which is:
```
https://seq.test.com/staging/ for staging ui
https://seq.test.com/prod/ for production ui
seq.test.com:6050 for staging ingestion
seq.test.com:6051 for prod ingestion
```

The problem is, in a kubernetes cluster, you can not forward non http ports using the ingress controller. Which is an issue with ingestion ports (I don't know how you managed to make it work). 
The only solution is to add an externalIPs to the ingestion service.

![image](https://user-images.githubusercontent.com/190756/83652616-1d769700-a5bb-11ea-92cb-b707b4af919e.png)

But your charts creates only one service containing both ui and ingestion: specifying an externalIP for it would expose both the ui and ingestion on it. And does not provide any variable to add this externalIP, requiring the creation of a new chart using your chart in a subchart.


A second point: i have been unable to correctly setup subpaths (using the same host) for 2 seq helm instances (staging and prod instances).

The `nginx.org/rewrites` annotation now requires specifying a serviceName defined in the same ingress.
You parameterized this service name using the helm chart name. There is no need to do that, it only makes things more complicated.
``` 
#the ingress created by helm:
http:
        paths:
        - backend:
            serviceName: seq-staging

#helm values.yaml
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: acme-issuer
    nginx.org/redirect-to-https: "true"
    nginx.org/rewrites: "serviceName=seq rewrite=/"
``` 

I'm still looking for a solution to this last problem.
