### ISSUE TITLE
Consider accepting ACCEPT_EULA to any value for docker images

### ISSUE THREAD

**Issue by skomis-mm** [datalust/seq-tickets#977]
Deploying seq through the ansible with dictionary syntax in yml config:
```yml
 seq:
   image: datalust/seq:5
   environment:
       ACCEPT_EULA: Y
```
results in converting `Y` to boolean value that results in failed startup.

The purpose is to relax this requirement to allow alternative values, or any like sql server for Linux [does](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-ver15#environment-variables).

Current workaround is to use 'list of strings' syntax:
```yml
environment:
  - ACCEPT_EULA=Y
```
